### PR TITLE
fix: `zipDirectory` too many open files

### LINKED ISSUE #362: too many open files bug in v4.x
### Description

v4 of `package:archive` appears to have a file descriptor leak (it appears to be somewhere in `zipDirectory`) which did not previously exist in v3.

### Reproduction Steps

1. Set file descriptor limit: `ulimit -s -n 100`
2. Run the following test using `package:archive` v3.0.0 (3.6.1)
3. Observe the test passes.
4. Upgrade `package:archive` to ^4.0.0 (4.0.1)
5. Re-run the test
6. Observe the test fails with "too many open files" error


**`pubspec.yaml`**

```diff
name: example
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
- archive: ^3.0.0
+ archive: ^4.0.0

dev_dependencies:
  test: ^1.0.0
```

**`archive_test.dart`**

```diff
import 'dart:io';
import 'dart:isolate';

import 'package:archive/archive_io.dart';
import 'package:test/test.dart';

Future<void> main() async {
  test('too many open files', () async {
    const numFiles = 500;
    final directoryToZip = Directory.systemTemp.createTempSync();
    for (var i = 0; i < numFiles; i++) {
      File('${directoryToZip.path}/$i.txt')
        ..createSync()
        ..writeAsStringSync('$i');
    }

    final tempDir = await Directory.systemTemp.createTemp();
    final zipFile = File('${tempDir.path}/test_archive.zip');
-   await Isolate.run(() {
-     ZipFileEncoder().zipDirectory(directoryToZip, filename: zipFile.path);
-   });
+   await Isolate.run(() async {
+     await ZipFileEncoder().zipDirectory(directoryToZip, filename: zipFile.path);
+   });
    expect(zipFile.existsSync(), isTrue);
  });
}
```

**Output from 3.6.1**

```sh
$ dart test
00:00 +1: All tests passed! 
```

**Output from 4.0.1**

```sh
✖ dart test
00:00 +0 -1: test/archive_test.dart: too many open files [E]                                                                                                                                                                                                                          
  FileSystemException: Cannot open file, path = '/var/folders/xx/qyf6zlzn3b34xcq6xzjb8vnh0000gn/T/sALEsG/111.txt' (OS Error: Too many open files, errno = 24)
  dart:io                                                _File.openSync
  package:archive/src/util/_file_handle_io.dart 35:16    FileHandle.open
  package:archive/src/util/_file_handle_io.dart 18:7     new FileHandle
  package:archive/src/util/input_file_stream.dart 50:20  new InputFileStream
  package:archive/src/io/zip_file_encoder.dart 136:24    ZipFileEncoder.addFile
  package:archive/src/io/zip_file_encoder.dart 128:13    ZipFileEncoder.addDirectory
  package:archive/src/io/zip_file_encoder.dart 36:11     ZipFileEncoder.zipDirectory
  test/archive_test.dart 20:30                           main.<fn>.<fn>
```

### PR DESCRIPTION
**Pull request by felangel**
closes #362

### CODE REVIEW

**Comment by eseidel** [comment]
Apropos of nothing, the Dart VM team once was lamenting to me that some of the dart:io async methods were a mistake.  async causes the Dart runtime to always exit back out to the event loop before performing the body of the method.  When just doing something like "stat" that's a lot of overhead for little gain.  This of course was all long before Isolates were easy to use.  These days Isolate.compute around at a top-level function to make the whole idea of "zip a directory" async could make a lot of sense, but the individual actions of the zipping I'd probably do with sync io methods within that isolate. 🤷

**Comment by brendan-duncan** [comment]
There are a lot of questionable designs, both in this library and in the Dart VM. What I wouldn't give for proper threads, memory safety be damned. This library has been around since before Dart 1.0, and it's seen a lot of changes to the language. I got through some of the tech debt baggage with the recent update, but it's still a bit of a mess.

Thanks a lot for the fix!

**Comment by brendan-duncan** [comment]
I'm getting an error that the test is trying to use deleteSync but the file is being used in another process. I'll poke at it some more, get it fixed up.

**Comment by brendan-duncan** [comment]
I suspect the issue is Windows being Windows, and sometimes it doesn't like to let go of a file if after you create it, even if you do everything synchronously. Might just need a delay before the delete.

**Comment by brendan-duncan** [comment]
I removed the delete, and had it output to a new directory, to avoid the race. It gets put into a temp folder anyways.

**Comment by brendan-duncan** [comment]
Yeah, that's essentially the issue that's come up. I haven't seen this problem before so it only happens in some situations, where doing an async close on the file and awaiting all of the promises at once, left too many file handles open in that case as they didn't close fast enough. There will likely be a slight performance hit waiting for each close before moving on to the next file, but I haven't measured the performance. It's dart, it's not exactly fast to begin with.

I do believe there are other places with the same "close async and wait after" pattern, in those extract* functions. I haven't had time to do another cleanup pass yet.

**Pull request merged**
