### PR TITLE
Upgrade dependency on crypto

### PR DESCRIPTION
**Pull request by zoechi**
- Upgrade dependency on crypto to `>=1.0.0 <2.0.0`
- fix use of deprecated `getUsage()` of the usage package
- update `.gitignore`

### CODE REVIEW

**Comment by brendan-duncan** [comment]
Thanks. Looks like I'll need to fix it up a bit more, the CI build is failing.  Haven't had much time for dart projects lately, hope they don't have too much bit rot.

**Comment by zoechi** [comment]
running the tests directly works fine but `pub run test` failed because of the way files are accessed. I wasn't sure if this was supposed to work

**Comment by brendan-duncan** [comment]
It used to work, but they kept changing the file access stuff with pub run test.  I seem to remember having the same issue with the image library tests.  I'll try and find some time tomorrow to fix it up again, can't bear seeing a red build status.

**Comment by brendan-duncan** [comment]
Actually, the drone.io CI build error came from it using 0.12.0 version of test, which depends on the older version of crypto.  The newer 0.12.13 version of test dropped the crypto dependency, but also depends on a newer version of the dart sdk than what seems to be available on drone.io.  I upped the test version dependency, and guess I'll just have to wait until the version of the sdk drone.io access catches up.

**Comment by brendan-duncan** [comment]
One more note on this since you didn't ask, seems drone.io is currently a dead-end all-together, it seems stuck on 1.10.1 version of the dart vm.  I'm just going to pull it off the read-me so I don't have to look at a red build that probably won't go green again until they fix that.

**Comment by zoechi** [comment]
I think you can use your own docker container to run tests in drone.io (just saw it mentioned in slack discussions - I haven't used drone.io myself since quite some time.

**Pull request merged**
