### PR TITLE
added one method to update specific file at index

### PR DESCRIPTION
**Pull request by alihassan143**

### CODE REVIEW

**Comment by alihassan143** [comment]
fixes 
[Docx_template](https://github.com/PavelS0/docx_template_dart/issues/53)
archive library is used in this library to add or update docx file so it needed to update some files in the archive files list

**Comment by alihassan143** [comment]
@brendan-duncan kindly review if any changes required

**Comment by alihassan143** [comment]
@brendan-duncan kindly review

**Comment by alihassan143** [comment]
@brendan-duncan any plans?

**Comment by wer-mathurin** [comment]
@brendan-duncan Any plan for a release date for Archive that will include this commit?

**Comment by brendan-duncan** [comment]
Sorry it's taking so long. I hope to get to it very soon. It's a major update version so I have to be a bit more careful than a minor release, but I've been sitting on it for too long so I should just do it.

**Pull request merged**
