### PR TITLE
Fix return type of `ArchiveFile.content` - it's always `List<int>`

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by kevmoo** [comment]
@devoncarew – could you look at this, too?

**Comment by kevmoo** [comment]
I guess not...this is a bit annoying...

**Comment by brendan-duncan** [comment]
too late, but lgtm anyways :-)

**Comment by kevmoo** [comment]
> too late, but lgtm anyways :-)

The one code path where `List<int>` isn't returned is a bit annoying...

Will ponder...

**Comment by brendan-duncan** [comment]
Oh you're right, I forgot I added that stream stuff in there which is
probably what throws off that assumption. I never did get that stream stuff
fully finished, turned out some details were harder than I anticipated.

**Pull request closed without merging**
