### PR TITLE
Support symlinks in ZIP archives and in extract functions

### LINKED ISSUE #104: Doesn't handle symlinks for .zip compress/decompress
I just checked the code.  .zip decompress isSymbolicLink doesn't do anything.  I can't compress or decompress archives with symlinks.  I see it's used for .tar, but not .zip.

### PR DESCRIPTION
**Pull request by blaugold**
Fixes #104

### CODE REVIEW

**Comment by brendan-duncan** [comment]
Thanks!

**Comment by blaugold** [comment]
@brendan-duncan Thanks for reviewing and merging the PR! If you can get around to it, I would appreciate a new release. 🙏

**Comment by brendan-duncan** [comment]
I'll push a release as soon as I get a chance, today or tomorrow.

**Comment by brendan-duncan** [comment]
I released 3.3.3 with the PR in it. Thanks again!

**Comment by blaugold** [comment]
Thank you @brendan-duncan!

**Pull request merged**
